name: dartdev

# This package is not intended for consumption on pub.dev. DO NOT publish.
publish_to: none

environment:
  sdk: '>=2.6.0 <3.0.0'
dependencies:
  analysis_server:
    path: ../analysis_server
  analysis_server_client:
    path: ../analysis_server_client
  analyzer:
    path: ../analyzer
  args: any
  cli_util: any
  dart2native:
    path: ../dart2native
  dart_style: any
  dds:
    path: ../dds
  devtools_server: any
  front_end:
    path: ../front_end
  intl: any
  meta:
    path: ../meta
  nnbd_migration:
    path: ../nnbd_migration
  path: any
  pub: any
  telemetry:
    path: ../telemetry
  usage: any

dev_dependencies:
  expect:
    path: ../expect
  lints: any
  pub_semver: any
  test: any
  yaml: any
